### ISSUE TITLE
Some reproducibilitea.org URLs include unescaped spaces

### ISSUE THREAD

**Issue by hertzsprung** [mjaquiery/reproducibiliTea#10]
e.g. https://reproducibilitea.org/journal club/administration/2019/10/21/zotero-library

Which breaks automatic linking on twitter and github 😉 I think these should either have a %20 or avoid spaces entirely.

**Comment by mjaquiery** [comment]
Thanks for noticing this. Seems Jekyll uses the categories of a post in the pathname, meaning that categories with spaces in break link parsers. I've changed the 'Journal club' category to 'JC'.
