### ISSUE TITLE
Add Home to menu?

### ISSUE THREAD

**Issue by jspickering** [mjaquiery/reproducibiliTea#12]
Currently to get back to the homepage you click on the ReproT logo. That's fine, unless you're me, and desperately looking for a button that says "Home" :sweat_smile: 

Could we add a link to "Home" just before the About link along the top?

**Comment by mjaquiery** [comment]
We were discussing redoing the menu to use a dropdown system. I think whether to include 'home' as a link would fall within that discussion. @OrbenAmy and @katiedrax are considering which options we want to include in the menus, iirc.

**Comment by mjaquiery** [comment]
We've changed the menus around, and Home now features prominently.
